version: '3.7'

networks: 
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

secrets:
  kong_db_dba_password:
    external: true
          
services:
  kong-db:
    image: 192.87.106.18:56001/postgres:0.1
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/psql:/var/lib/postgresql/data
    secrets:
      - kong_db_dba_password
    networks:
      - $STACK_NETWORK
    environment:
      POSTGRES_DB:       api-gw
      POSTGRES_USER:     kong
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/kong_db_dba_password
      
  kong-oidc:
    image: 192.87.106.18:56001/kong-oidc:0.1
    secrets:
      - kong_db_dba_password
    depends_on:
      - kong-db
    networks:
      - $STACK_NETWORK
    ports:
      - $STACK_PORT:8000
      - $STACK_PORT_ADMIN:8001
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          ${STACK_SERVICE}_kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      api-gw
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_db_dba_password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000
      KONG_ADMIN_LISTEN:     0.0.0.0:8001
      KONG_PLUGINS:          oidc

  konga:
    image: 192.87.106.18:56001/konga:0.1
    secrets:
      - kong_db_dba_password
    networks:
      - $STACK_NETWORK
    command: "-c prepare_docker_env -a postgres"
    deploy:
      replicas: 1
      restart_policy:
        condition: none  
    ports:
      - $STACK_PORT_ADMIN2:1337
    environment:
      NODE_ENV:         prep
      TOKEN_SECRET:     rwekaneewnkan
      DB_ADAPTER:       postgres
      DB_HOST:          ${STACK_SERVICE}_kong-db
      DB_PORT:          5432
      DB_USER:          kong
      DB_MYUSER:        kong
      DB_PASSWORD_FILE: /run/secrets/kong_db_dba_password
      DB_DATABASE:      konga_database
      KONGA_HOOK_TIMEOUT: 120000
