version: '3.7'

networks: 
  appnet:
    external: true

volumes:
  kong-datastore:

secrets:
  kong_db_dba_password:
    external: true
          
          
services:
  kong-db:
    image: postgres:9.6
    volumes:
      - .data/kong/psql:/var/lib/postgresql/data
    secrets:
      - kong_db_dba_password
    networks:
      - appnet
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB:       api-gw
      POSTGRES_USER:     kong
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/kong_db_dba_password

  kong:
    image: kong
    build: ../image-kong/
    secrets:
      - kong_db_dba_password
    depends_on:
      - kong-db
    networks:
      - appnet
    ports:
      - "8000:8000" # Listener
      - "8001:8001" # Admin API
      - "8443:8443" # Listener  (SSL)
      - "8444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      api-gw
      KONG_PG_DB_PASSWORD_FILE: /run/secrets/kong_db_dba_password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          oidc

  konga:
    image: konga
    build: ../image-konga/
    secrets:
      - kong_db_dba_password
    depends_on: 
      - kong
    networks:
      - appnet
    ports:
      - "1337:1337" # Port for API frontend
    environment:
      NODE_ENV:         production
      TOKEN_SECRET:     rwekaneewnkan
      DB_ADAPTER:       postgres
      DB_HOST:          kong-db
      DB_PORT:          5432
      DB_USER:          kong
      DB_MYUSER:        kong
      DB_PASSWORD_FILE: /run/secrets/kong_db_dba_password
      DB_DATABASE:      konga_database
      KONGA_HOOK_TIMEOUT: 120000
